task10_11_13/calculate/calc/urls.py
from django.urls import path

from . import views

app_name = 'calc'
urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('calc/', views.IndexView.as_view(), name='index'),
    path('calc/api/', views.ApiView.as_view(), name='api'),
    path('calc/history/', views.HistoryView.as_view(), name='history'),
]

task10_11_13/calculate/calculate/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('calc.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

task10_11_13/calculate/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

task10_11_13/calculate/calc/models.py
from django.db import models


class Operator(models.Model):
    operator = models.CharField(max_length=10)
    operator_info = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.operator


class Operation(models.Model):
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE)
    arg1 = models.FloatField()
    arg2 = models.FloatField()
    operation_text = models.CharField(max_length=200, default='')
    pub_date = models.DateTimeField('date published')
    result = models.FloatField(default=0)

    def __str__(self):
        return self.operation_text

task10_11_13/calculate/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

__all__ = {'Question', 'Choice'}


class Question(models.Model):
    question_text: str = models.CharField(max_length=200)
    pub_date: datetime.datetime = models.DateTimeField('date published')

    def __str__(self) -> str:
        return self.question_text

    def was_published_recently(self) -> bool:
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> models.CharField:
        return self.choice_text

task10_11_13/calculate/calc/views.py
from django.utils import timezone
from django.views import generic
from django.http import JsonResponse, HttpResponse, QueryDict
from .models import Operator, Operation
from django.shortcuts import get_object_or_404, render

from .mat_calc import calc

__all__ = {'MainView', 'IndexView', 'HistoryView'}

OPERATORS = {'add': '+', 'sub': '-', 'mul': '*', 'div': '/'}
API_KEYS = ['arg1', 'arg2', 'act', 'add', 'sub', 'mul', 'div', 'history']


def calculate(post: QueryDict):
    rslt = Operation(
            operator=get_object_or_404(Operator, operator=post['act']),
            arg1=post['arg1'],
            arg2=post['arg2'],
            pub_date=timezone.now(),
            )
    try:
        rslt.result = calc(str(rslt.operator), rslt.arg1, rslt.arg2)
    except Exception as e:
        rslt = e
    else:
        rslt.operation_text = f'{rslt.arg1 if float(rslt.arg1) >= 0 else "(" + rslt.arg1 + ")"} ' \
                              f'{rslt.operator} ' \
                              f'{rslt.arg2 if float(rslt.arg2) >= 0 else "(" + rslt.arg2 + ")"} ' \
                              f'= {rslt.result}'
        rslt.save()
    return rslt


class MainView(generic.View):
    template_name = 'calc/main.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class ApiView(generic.View):

    def get(self, request):
        result = request.GET.copy()
        if len(result.keys()) and set(result.keys()).issubset(API_KEYS):
            if {'act', 'arg1', 'arg2'}.issubset(result.keys()) and result['act'] in OPERATORS.keys():
                result.update({'act': OPERATORS[result['act']]})
                el = calculate(result)
                result = request.GET.copy()
                if type(el) is Operation:
                    result.update({'result': el.result})
                elif isinstance(el, Exception):
                    result.update({'result': str(el), 'error': type(el).__name__})
                return JsonResponse(result)
            if 'history' in result.keys():
                result.update({'result': [el.operation_text
                                          for el in Operation.objects.order_by('-pub_date')[:int(result['history'])]]})
                return JsonResponse(result)

        return HttpResponse(f'<h3>Empty or wrong API request.</h3><br>' 
                            f'For example,<br>' 
                            f'<i>?arg1=45&arg2=9&act=div<br>'
                            f'?history=5<br><br></i>'
                            f'For errors,<br>'
                            f'<i>?arg1=5&arg2=<b>0</b>&act=div</i> - division by zero<br>'
                            f'<i>?arg1=5&arg2=<b>2s</b>&act=div</i> - invalid argument')


class IndexView(generic.ListView):
    template_name = 'calc/index.html'

    def get(self, request, *args, **kwargs):
        operator_list = Operator.objects.all()
        context = {'operator_list': operator_list}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = {}
        try:
            operator_curr = get_object_or_404(
                Operator,
                pk=request.POST['operator_selected']
            )
        except (KeyError, Operator.DoesNotExist):
            return render(
                request,
                'calc/index.html',
                {'error_message': "You didn't select a operator or enter operand"}
            )
        else:
            r = request.POST.copy()
            r.update({'act': str(operator_curr)})
            context.update({'arg1': r['arg1'], 'arg2': r['arg2'],
                            'selected_id': int(r['operator_selected'])})
            el = calculate(r)
            if type(el) is Operation:
                context.update({'result': el.result})
            elif isinstance(el, Exception):
                context.update({'result': str(el), 'error': type(el).__name__})

        operator_list = Operator.objects.all()
        context.update({'operator_list': operator_list})
        return render(request, self.template_name, context)


class HistoryView(generic.ListView):
    template_name = 'calc/history.html'
    context_object_name = 'operation_list'

    def get_queryset(self):
        return Operation.objects.order_by('-pub_date')[:10]

task10_11_13/calculate/polls/views.py
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect

from .models import Choice, Question

__all__ = {'IndexView', 'DetailView', 'ResultsView', 'vote'}


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    if 'choice' not in request.POST:
        return render(request, 'polls/detail.html', dict(
            question=question,
            error_message="You aren't set a choice",
        ))

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except Choice.DoesNotExist:
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', dict(
            question=question,
            error_message="Undefined choice",
        ))

    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

task10_11_13/calculate/calc/templates/calc/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>История последних {{ operation_list.count }} операций</title>
</head>
<body>
    <a href="{% url 'calc:main' %}">Главная</a>
    <p>Последних {{ operation_list.count }} операций</p>

    <ul>
    {% for operation_curr in operation_list %}
        <li>{{ operation_curr.operation_text }}</li>
    {% endfor %}
    </ul>
    <br>
    <a href="{% url 'calc:index' %}">Калькулятор</a>
</body>
</html>

task10_11_13/calculate/calc/templates/calc/index.html
{% if operator_list %}
<a href="{% url 'calc:main' %}">Главная</a>
<form action="{% url 'calc:index' %}" method="post"> {% csrf_token %}
    <h1>Калькулятор</h1>
    <input type="text" size="10" name="arg1" value="{{ arg1 }}">
    <select size=1 name="operator_selected">
        <option selected disabled>Выберите оператор</option>
    {% for operator in operator_list %}
        <option
            {% if operator.id == selected_id %} selected {% endif %}
            value="{{ operator.id }}">{{ operator.operator }}</option>
    {% endfor %}
    </select>
    <input type="text" size="10" name="arg2" value="{{ arg2 }}">
    <input type="submit" value="Вычислить">
    <br>
    <p>Результат: {{ result }}</p>
  </form>
  <br>
  <a href="{% url 'calc:history' %}">История</a>
{% else %}
    <p>You didn't select a operator or enter operand for calculate.</p>
{% endif %}

task10_11_13/calculate/calc/templates/calc/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
</head>
<body>
    <a href="{% url 'calc:index' %}">Калькулятор</a> (db.sqlite3)
    <br><br>
    <a href="{% url 'calc:api' %}">Калькулятор API</a> (db.sqlite3)
    <br><br>
    <a href="{% url 'polls:index' %}">Polls</a> (polls_db.sqlite3)
</body>
</html>

task10_11_13/calculate/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Question №{{ question.id }}</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
        <input type="submit" value="Vote">
    </form>
</body>
</html>

task10_11_13/calculate/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls Index</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

task10_11_13/calculate/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results for Question №{{ question.id }}</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} – {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>