task12/filer/file_loader/urls.py
from django.urls import path

from . import views

app_name = 'fileloader'
urlpatterns = [
    path('fileloader/', views.IndexView.as_view(), name='index'),
    path('fileloader/results/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('fileloader/results/', views.ResultsView.as_view(), name='results'),
]

task12/filer/filer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('file_loader.urls')),
    path('admin/', admin.site.urls),
]

task12/filer/file_loader/models.py
from django.db import models
from jsonfield import JSONField


class FileItem(models.Model):
    title = models.CharField(max_length=50)
    json_data = JSONField()

    def __str__(self):
        return self.title

task12/filer/file_loader/views.py
import json
from django.urls import reverse
from django.shortcuts import render
from django.utils.datastructures import MultiValueDictKeyError
from django.views import generic
from .models import FileItem
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse, HttpResponse, QueryDict, HttpResponseRedirect


SIGN_DEL = ['"', '(', ')', '-', '?', "'", '\\n']

__all__ = {'IndexView', 'DetailView', 'ResultsView'}


class IndexView(generic.ListView):
    template_name = 'fileloader/index.html'

    def get(self, request, *args, **kwargs):
        # operator_list = Operator.objects.all()
        # context = {'operator_list': operator_list}
        context = {'error': False}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = {}
        try:
            f = request.FILES['file_path']
            obj, created = FileItem.objects.get_or_create(title=f.name)
            if not created:
                raise Exception('Файл уже загружен. Повторите выбор.')
            if f.content_type != 'text/plain':
                raise Exception('Файл не текстовый. Повторите выбор.')
            file = f.read()
        except MultiValueDictKeyError:
            return render(request, 'fileloader/index.html',
                          {'error': 'Файл не загружен. Повторите выбор.'})
        except Exception as e:
            return render(request, 'fileloader/index.html', {'error': e})
        else:
            file = str(file)
            for sign in SIGN_DEL:
                file = file.replace(sign, ' ')
            file = file.split()
            result = {}
            for word in file:
                result[word] = result.setdefault(word, 0) + 1
            obj.json_data = json.dumps(result)
            obj.save()
            return HttpResponseRedirect(reverse('fileloader:results'))


class DetailView(generic.ListView):
    model = FileItem
    template_name = 'fileloader/detail.html'

    def get(self, request, *args, **kwargs):
        file = FileItem.objects.get(id=kwargs['pk'])
        words_list = {key: str(value) for key, value in json.loads(file.json_data).items()}
        context = {'file_title': file.title, 'words_list': words_list}
        return render(request, self.template_name, context)


class ResultsView(generic.ListView):
    template_name = 'fileloader/results.html'
    context_object_name = 'files_list'

    def get_queryset(self):
        return FileItem.objects.all()

task12/filer/file_loader/templates/fileloader/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
 <head>
    <meta charset="UTF-8">
    <title>Результаты {{ file_title }}</title>
    <link rel="stylesheet" href="{% static 'css/temp.css' %}">
 </head>
 <body>
  <a href="{% url 'fileloader:index' %}">Главная</a><br>
  <br>
  <table>
   <caption>Таблица для {{ file_title }}</caption>
   <tr>
    <th>Слово</th>
    <th>Количество</th>
   </tr>
   {% for key,value in words_list.items %}
   <tr>
       <td>{{ key }}</td><td>{{ value }}</td>
   </tr>
   {% endfor %}
  </table>
 </body>
</html>

task12/filer/file_loader/templates/fileloader/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File loader</title>
</head>
<body>
<a href="{% url 'fileloader:index' %}">Главная</a>
{% if not error %}
  <form action="{% url 'fileloader:index' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
    <h1>Загрузка файла</h1>
    <input type="file" size="20" name="file_path">
    <br> <br>
    <input type="submit" value="Загрузить">
    <br> <br>
  </form>
  <br>
  <a href="{% url 'fileloader:results' %}">Список загрузок</a>
{% else %}
    <p>{{error}}</p>
{% endif %}
</body>
</html>

task12/filer/file_loader/templates/fileloader/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список загрузок</title>
</head>
<body>
    <a href="{% url 'fileloader:index' %}">Главная</a><br>
    <br>
{% if files_list %}
    <p>Список загрузок</p>
    <ul>
        {% for file in files_list %}
        <li><a href="{% url 'fileloader:detail' file.id %}">{{ file.title }}</a></li>
        {% endfor %}
    </ul>
    <br>
{% else %}
    <p>Загруженые файлы отсутствуют.</p>
{% endif %}
</body>
</html>